In [2]:
import numpy as np
import pandas as pd
X = pd.read_csv('../datasets/data_2d.csv', header=None)

In [3]:
# Dataframes do not act the same as numpy arrays
X[0,0]  # numpy syntax

KeyError: (0, 0)

In [4]:
# Convert to an array
M = X.as_matrix() # poorly named
type(M)

numpy.ndarray

In [5]:
# Get single series in dataframe - A column
X[0]

0     17.930201
1     97.144697
2     81.775901
3     55.854342
4     49.366550
5      3.192702
6     49.200784
7     21.882804
8     79.509863
9     88.153887
10    60.743854
11    67.415582
12    48.318116
13    28.829972
14    43.853743
15    25.313694
16    10.807727
17    98.365746
18    29.146910
19    65.100302
20    24.644113
21    37.559805
22    88.164506
23    13.834621
24    64.410844
25    68.925992
26    39.488442
27    52.463178
28    48.484787
29     8.062088
        ...
70    30.187692
71    11.788418
72    18.292424
73    96.712668
74    31.012739
75    11.397261
76    17.392556
77    72.182694
78    73.980021
79    94.493058
80    84.562821
81    51.742474
82    53.748590
83    85.050835
84    46.777250
85    49.758434
86    24.119257
87    27.201576
88     7.009596
89    97.646950
90     1.382983
91    22.323530
92    45.045406
93    40.163991
94    53.182740
95    46.456779
96    77.130301
97    68.600608
98    41.693887
99     4.142669
Name: 0, dtype: float64

## Important Distinction between Pandas and Numpy

- Numpy: `X[0]` -> Returns 0th row
- Pandas: `X[0]` -> Returns column that has name `0`

In [7]:
# How to get a row in pandas
X.iloc[0]

0     17.930201
1     94.520592
2    320.259530
Name: 0, dtype: float64

In [8]:
X.ix[0]

0     17.930201
1     94.520592
2    320.259530
Name: 0, dtype: float64

In [9]:
# Select multiple columns 
X[[0,2]]

            0           2
0   17.930201  320.259530
1   97.144697  404.634472
2   81.775901  181.485108
3   55.854342  321.773638
4   49.366550  322.465486
5    3.192702   94.618811
6   49.200784  356.348093
7   21.882804  181.653769
8   79.509863  423.557743
9   88.153887  369.229245
10  60.743854  427.605804
11  67.415582  292.471822
12  48.318116  395.529811
13  28.829972  319.031348
14  43.853743  287.428144
15  25.313694  292.768909
16  10.807727  159.663308
17  98.365746  438.798964
18  29.146910  250.986309
19  65.100302  231.711508
20  24.644113  163.398161
21  37.559805   83.480155
22  88.164506  466.265806
23  13.834621  100.886430
24  64.410844  365.641048
25  68.925992  426.140015
26  39.488442  235.532389
27  52.463178  283.291640
28  48.484787  298.581440
29   8.062088  309.234109
..        ...         ...
70  30.187692   89.539008
71  11.788418  181.550683
72  18.292424  224.773383
73  96.712668  219.567094
74  31.012739  298.490216
75  11.397261  199.944045
76  17.392556   43.915692
77  72.182694  256.068378
78  73.980021  159.372581
79  94.493058  447.132704
80  84.562821  233.078830
81  51.742474  131.070180
82  53.748590  298.814333
83  85.050835  451.803523
84  46.777250  368.366436
85  49.758434  254.706774
86  24.119257  168.308433
87  27.201576  146.342260
88   7.009596  176.810149
89  97.646950  219.160280
90   1.382983  252.905653
91  22.323530  127.570479
92  45.045406  375.822340
93  40.163991   80.389019
94  53.182740  142.718183
95  46.456779  336.876154
96  77.130301  438.460586
97  68.600608  355.900287
98  41.693887  284.834637
99   4.142669  168.034401

[100 rows x 2 columns]

In [10]:
# Select all rows where 0th column is < 5
X[X[0] < 5]

           0          1           2
5   3.192702  29.256299   94.618811
44  3.593966  96.252217  293.237183
54  4.593463  46.335932  145.818745
90  1.382983  84.944087  252.905653
99  4.142669  52.254726  168.034401